<?php
            $options = [
                ['value' => '', 'label' => 'Seleccione cantón'],
                ['value' => 'San José', 'region_id' => '609', 'label' => 'San José'],
                ['value' => 'Escazú', 'region_id' => '609', 'label' => 'Escazú'],
                ['value' => 'Desamparados', 'region_id' => '609', 'label' => 'Desamparados'],
                ['value' => 'Puriscal', 'region_id' => '609', 'label' => 'Puriscal'],
                ['value' => 'Tarrazu', 'region_id' => '609', 'label' => 'Tarrazu'],
                ['value' => 'Aserrí', 'region_id' => '609', 'label' => 'Aserrí'],
                ['value' => 'Mora', 'region_id' => '609', 'label' => 'Mora'],
                ['value' => 'Goicoechea', 'region_id' => '609', 'label' => 'Goicoechea'],
                ['value' => 'Santa Ana', 'region_id' => '609', 'label' => 'Santa Ana'],
                ['value' => 'Alajuelita', 'region_id' => '609', 'label' => 'Alajuelita'],
                ['value' => 'Vazquez de Coronado', 'region_id' => '609', 'label' => 'Vazquez de Coronado'],
                ['value' => 'Acosta', 'region_id' => '609', 'label' => 'Acosta'],
                ['value' => 'Tibás', 'region_id' => '609', 'label' => 'Tibás'],
                ['value' => 'Moravia', 'region_id' => '609', 'label' => 'Moravia'],
                ['value' => 'Montes de Oca', 'region_id' => '609', 'label' => 'Montes de Oca'],
                ['value' => 'Turrubares', 'region_id' => '609', 'label' => 'Turrubares'],
                ['value' => 'Dota', 'region_id' => '609', 'label' => 'Dota'],
                ['value' => 'Curridabat', 'region_id' => '609', 'label' => 'Curridabat'],
                ['value' => 'Pérez Zeledón', 'region_id' => '609', 'label' => 'Pérez Zeledón'],
                ['value' => 'León Cortes', 'region_id' => '609', 'label' => 'León Cortes'],
                ['value' => 'Alajuela', 'region_id' => '610', 'label' => 'Alajuela'],
                ['value' => 'San Ramon', 'region_id' => '610', 'label' => 'San Ramon'],
                ['value' => 'Grecia', 'region_id' => '610', 'label' => 'Grecia'],
                ['value' => 'San Mateo', 'region_id' => '610', 'label' => 'San Mateo'],
                ['value' => 'Atenas', 'region_id' => '610', 'label' => 'Atenas'],
                ['value' => 'Naranjo', 'region_id' => '610', 'label' => 'Naranjo'],
                ['value' => 'Palmares', 'region_id' => '610', 'label' => 'Palmares'],
                ['value' => 'Poás', 'region_id' => '610', 'label' => 'Poás'],
                ['value' => 'Orotina', 'region_id' => '610', 'label' => 'Orotina'],
                ['value' => 'San Carlos', 'region_id' => '610', 'label' => 'San Carlos'],
                ['value' => 'Alfaro Ruiz', 'region_id' => '610', 'label' => 'Alfaro Ruiz'],
                ['value' => 'Valverde Vega', 'region_id' => '610', 'label' => 'Valverde Vega'],
                ['value' => 'Upala', 'region_id' => '610', 'label' => 'Upala'],
                ['value' => 'Los Chiles', 'region_id' => '610', 'label' => 'Los Chiles'],
                ['value' => 'Guatuso', 'region_id' => '610', 'label' => 'Guatuso'],
                ['value' => 'Cartago', 'region_id' => '611', 'label' => 'Cartago'],
                ['value' => 'Paraíso', 'region_id' => '611', 'label' => 'Paraíso'],
                ['value' => 'La Unión', 'region_id' => '611', 'label' => 'La Unión'],
                ['value' => 'Jiménez', 'region_id' => '611', 'label' => 'Jiménez'],
                ['value' => 'Turrialba', 'region_id' => '611', 'label' => 'Turrialba'],
                ['value' => 'Alvarado', 'region_id' => '611', 'label' => 'Alvarado'],
                ['value' => 'Oreamuno', 'region_id' => '611', 'label' => 'Oreamuno'],
                ['value' => 'El Guarco', 'region_id' => '611', 'label' => 'El Guarco'],
                ['value' => 'Heredia', 'region_id' => '612', 'label' => 'Heredia'],
                ['value' => 'Barva', 'region_id' => '612', 'label' => 'Barva'],
                ['value' => 'Santo Domingo', 'region_id' => '612', 'label' => 'Santo Domingo'],
                ['value' => 'Santa Bárbara', 'region_id' => '612', 'label' => 'Santa Bárbara'],
                ['value' => 'San Rafael', 'region_id' => '612', 'label' => 'San Rafael'],
                ['value' => 'San Isidro', 'region_id' => '612', 'label' => 'San Isidro'],
                ['value' => 'Belén', 'region_id' => '612', 'label' => 'Belén'],
                ['value' => 'San Joaquín de Flores', 'region_id' => '612', 'label' => 'San Joaquín de Flores'],
                ['value' => 'San Pablo', 'region_id' => '612', 'label' => 'San Pablo'],
                ['value' => 'Sarapiquí', 'region_id' => '612', 'label' => 'Sarapiquí'],
                ['value' => 'Liberia', 'region_id' => '613', 'label' => 'Liberia'],
                ['value' => 'Nicoya', 'region_id' => '613', 'label' => 'Nicoya'],
                ['value' => 'Santa Cruz', 'region_id' => '613', 'label' => 'Santa Cruz'],
                ['value' => 'Bagaces', 'region_id' => '613', 'label' => 'Bagaces'],
                ['value' => 'Carrillo', 'region_id' => '613', 'label' => 'Carrillo'],
                ['value' => 'Cañas', 'region_id' => '613', 'label' => 'Cañas'],
                ['value' => 'Abangares', 'region_id' => '613', 'label' => 'Abangares'],
                ['value' => 'Tilarán', 'region_id' => '613', 'label' => 'Tilarán'],
                ['value' => 'Nandayure', 'region_id' => '613', 'label' => 'Nandayure'],
                ['value' => 'La Cruz', 'region_id' => '613', 'label' => 'La Cruz'],
                ['value' => 'Hojancha', 'region_id' => '613', 'label' => 'Hojancha'],
                ['value' => 'Puntarenas', 'region_id' => '614', 'label' => 'Puntarenas'],
                ['value' => 'Esparza', 'region_id' => '614', 'label' => 'Esparza'],
                ['value' => 'Buenos Aires', 'region_id' => '614', 'label' => 'Buenos Aires'],
                ['value' => 'Montes de Oro', 'region_id' => '614', 'label' => 'Montes de Oro'],
                ['value' => 'Osa', 'region_id' => '614', 'label' => 'Osa'],
                ['value' => 'Aguirre', 'region_id' => '614', 'label' => 'Aguirre'],
                ['value' => 'Golfito', 'region_id' => '614', 'label' => 'Golfito'],
                ['value' => 'Coto Brus', 'region_id' => '614', 'label' => 'Coto Brus'],
                ['value' => 'Parrita', 'region_id' => '614', 'label' => 'Parrita'],
                ['value' => 'Corredores', 'region_id' => '614', 'label' => 'Corredores'],
                ['value' => 'Garabito', 'region_id' => '614', 'label' => 'Garabito'],
                ['value' => 'Limón', 'region_id' => '615', 'label' => 'Limón'],
                ['value' => 'Pococí', 'region_id' => '615', 'label' => 'Pococí'],
                ['value' => 'Siquirres', 'region_id' => '615', 'label' => 'Siquirres'],
                ['value' => 'Talamanca', 'region_id' => '615', 'label' => 'Talamanca'],
                ['value' => 'Matina', 'region_id' => '615', 'label' => 'Matina'],
                ['value' => 'Guácimo', 'region_id' => '615', 'label' => 'Guácimo']
            ];
			
			echo json_encode($options, JSON_PRETTY_PRINT);