<?php
            $options = [                
				['value' => '', 'label' => 'Seleccione distrito'],
                ['value' => 'Carmen', 'city' => 'San José', 'label' => 'Carmen'],
                ['value' => 'Merced', 'city' => 'San José', 'label' => 'Merced'],
                ['value' => 'Hospital', 'city' => 'San José', 'label' => 'Hospital'],
                ['value' => 'Catedral', 'city' => 'San José', 'label' => 'Catedral'],
                ['value' => 'Zapote', 'city' => 'San José', 'label' => 'Zapote'],
                ['value' => 'San Francisco de Dos Ríos', 'city' => 'San José', 'label' => 'San Francisco de Dos Ríos'],
                ['value' => 'Uruca', 'city' => 'San José', 'label' => 'Uruca'],
                ['value' => 'Mata Redonda', 'city' => 'San José', 'label' => 'Mata Redonda'],
                ['value' => 'Pavas', 'city' => 'San José', 'label' => 'Pavas'],
                ['value' => 'Hatillo', 'city' => 'San José', 'label' => 'Hatillo'],
                ['value' => 'San Sebastián', 'city' => 'San José', 'label' => 'San Sebastián'],
                ['value' => 'Escazú', 'city' => 'Escazú', 'label' => 'Escazú'],
                ['value' => 'San Antonio', 'city' => 'Escazú', 'label' => 'San Antonio'],
                ['value' => 'San Rafael', 'city' => 'Escazú', 'label' => 'San Rafael'],
                ['value' => 'Desamparados', 'city' => 'Desamparados', 'label' => 'Desamparados'],
                ['value' => 'San Miguel', 'city' => 'Desamparados', 'label' => 'San Miguel'],
                ['value' => 'San Juan de Dios', 'city' => 'Desamparados', 'label' => 'San Juan de Dios'],
                ['value' => 'San Rafael Arriba', 'city' => 'Desamparados', 'label' => 'San Rafael Arriba'],
                ['value' => 'San Antonio', 'city' => 'Desamparados', 'label' => 'San Antonio'],
                ['value' => 'Frailes', 'city' => 'Desamparados', 'label' => 'Frailes'],
                ['value' => 'Patarra', 'city' => 'Desamparados', 'label' => 'Patarra'],
                ['value' => 'San Cristobal', 'city' => 'Desamparados', 'label' => 'San Cristobal'],
                ['value' => 'Rosario', 'city' => 'Desamparados', 'label' => 'Rosario'],
                ['value' => 'Damas', 'city' => 'Desamparados', 'label' => 'Damas'],
                ['value' => 'San Rafael Abajo', 'city' => 'Desamparados', 'label' => 'San Rafael Abajo'],
                ['value' => 'Gravilias', 'city' => 'Desamparados', 'label' => 'Gravilias'],
                ['value' => 'Los Guido', 'city' => 'Desamparados', 'label' => 'Los Guido'],
                ['value' => 'Santiago', 'city' => 'Puriscal', 'label' => 'Santiago'],
                ['value' => 'Mercedes Sur', 'city' => 'Puriscal', 'label' => 'Mercedes Sur'],
                ['value' => 'Barbacoas', 'city' => 'Puriscal', 'label' => 'Barbacoas'],
                ['value' => 'Grifo Alto', 'city' => 'Puriscal', 'label' => 'Grifo Alto'],
                ['value' => 'San Rafael', 'city' => 'Puriscal', 'label' => 'San Rafael'],
                ['value' => 'Candelaria', 'city' => 'Puriscal', 'label' => 'Candelaria'],
                ['value' => 'Desamparaditos', 'city' => 'Puriscal', 'label' => 'Desamparaditos'],
                ['value' => 'San Antonio', 'city' => 'Puriscal', 'label' => 'San Antonio'],
                ['value' => 'Chires', 'city' => 'Puriscal', 'label' => 'Chires'],
                ['value' => 'San Marcos', 'city' => 'Tarrazu', 'label' => 'San Marcos'],
                ['value' => 'San Lorenzo', 'city' => 'Tarrazu', 'label' => 'San Lorenzo'],
                ['value' => 'San Carlos', 'city' => 'Tarrazu', 'label' => 'San Carlos'],
                ['value' => 'Aserrí', 'city' => 'Aserrí', 'label' => 'Aserrí'],
                ['value' => 'Tarbaca', 'city' => 'Aserrí', 'label' => 'Tarbaca'],
                ['value' => 'Vuelta de Jorco', 'city' => 'Aserrí', 'label' => 'Vuelta de Jorco'],
                ['value' => 'San Gabriel', 'city' => 'Aserrí', 'label' => 'San Gabriel'],
                ['value' => 'Legua', 'city' => 'Aserrí', 'label' => 'Legua'],
                ['value' => 'Monterrey', 'city' => 'Aserrí', 'label' => 'Monterrey'],
                ['value' => 'Salitrillos', 'city' => 'Aserrí', 'label' => 'Salitrillos'],
                ['value' => 'Colón', 'city' => 'Mora', 'label' => 'Colón'],
                ['value' => 'Guayabo', 'city' => 'Mora', 'label' => 'Guayabo'],
                ['value' => 'Tabarcia', 'city' => 'Mora', 'label' => 'Tabarcia'],
                ['value' => 'Piedras Negras', 'city' => 'Mora', 'label' => 'Piedras Negras'],
                ['value' => 'Picagres', 'city' => 'Mora', 'label' => 'Picagres'],
                ['value' => 'Guadalupe', 'city' => 'Goicoechea', 'label' => 'Guadalupe'],
                ['value' => 'San Francisco', 'city' => 'Goicoechea', 'label' => 'San Francisco'],
                ['value' => 'Calle Blancos', 'city' => 'Goicoechea', 'label' => 'Calle Blancos'],
                ['value' => 'Mata de Plátano', 'city' => 'Goicoechea', 'label' => 'Mata de Plátano'],
                ['value' => 'Ipís', 'city' => 'Goicoechea', 'label' => 'Ipís'],
                ['value' => 'Rancho Redondo', 'city' => 'Goicoechea', 'label' => 'Rancho Redondo'],
                ['value' => 'Purral', 'city' => 'Goicoechea', 'label' => 'Purral'],
                ['value' => 'Santa Ana', 'city' => 'Santa Ana', 'label' => 'Santa Ana'],
                ['value' => 'Salitral', 'city' => 'Santa Ana', 'label' => 'Salitral'],
                ['value' => 'Pozos', 'city' => 'Santa Ana', 'label' => 'Pozos'],
                ['value' => 'Uruca', 'city' => 'Santa Ana', 'label' => 'Uruca'],
                ['value' => 'Piedades', 'city' => 'Santa Ana', 'label' => 'Piedades'],
                ['value' => 'Brasil', 'city' => 'Santa Ana', 'label' => 'Brasil'],
                ['value' => 'Alajuelita', 'city' => 'Alajuelita', 'label' => 'Alajuelita'],
                ['value' => 'San Josecito', 'city' => 'Alajuelita', 'label' => 'San Josecito'],
                ['value' => 'San Antonio', 'city' => 'Alajuelita', 'label' => 'San Antonio'],
                ['value' => 'Concepción', 'city' => 'Alajuelita', 'label' => 'Concepción'],
                ['value' => 'San Felipe', 'city' => 'Alajuelita', 'label' => 'San Felipe'],
                ['value' => 'San Isidro', 'city' => 'Vazquez de Coronado', 'label' => 'San Isidro'],
                ['value' => 'San Rafael', 'city' => 'Vazquez de Coronado', 'label' => 'San Rafael'],
                ['value' => 'Dulce Nombre de Jesús', 'city' => 'Vazquez de Coronado', 'label' => 'Dulce Nombre de Jesús'],
                ['value' => 'Patalillo', 'city' => 'Vazquez de Coronado', 'label' => 'Patalillo'],
                ['value' => 'Cascajal', 'city' => 'Vazquez de Coronado', 'label' => 'Cascajal'],
                ['value' => 'San Ignacio de Acosta', 'city' => 'Acosta', 'label' => 'San Ignacio de Acosta'],
                ['value' => 'Guaitil', 'city' => 'Acosta', 'label' => 'Guaitil'],
                ['value' => 'Palmichal', 'city' => 'Acosta', 'label' => 'Palmichal'],
                ['value' => 'Cangrejal', 'city' => 'Acosta', 'label' => 'Cangrejal'],
                ['value' => 'Sabanillas', 'city' => 'Acosta', 'label' => 'Sabanillas'],
                ['value' => 'San Juan', 'city' => 'Tibás', 'label' => 'San Juan'],
                ['value' => 'Cinco esquinas', 'city' => 'Tibás', 'label' => 'Cinco esquinas'],
                ['value' => 'Anselmo Llorente', 'city' => 'Tibás', 'label' => 'Anselmo Llorente'],
                ['value' => 'Leon XIII', 'city' => 'Tibás', 'label' => 'Leon XIII'],
                ['value' => 'Colima', 'city' => 'Tibás', 'label' => 'Colima'],
                ['value' => 'San Vicente', 'city' => 'Moravia', 'label' => 'San Vicente'],
                ['value' => 'San Jerónimo', 'city' => 'Moravia', 'label' => 'San Jerónimo'],
                ['value' => 'Trinidad', 'city' => 'Moravia', 'label' => 'Trinidad'],
                ['value' => 'San Pedro', 'city' => 'Montes de Oca', 'label' => 'San Pedro'],
                ['value' => 'Sabanilla', 'city' => 'Montes de Oca', 'label' => 'Sabanilla'],
                ['value' => 'Mercedes', 'city' => 'Montes de Oca', 'label' => 'Mercedes'],
                ['value' => 'San Rafael', 'city' => 'Montes de Oca', 'label' => 'San Rafael'],
                ['value' => 'San Pablo', 'city' => 'Turrubares', 'label' => 'San Pablo'],
                ['value' => 'San Pedro', 'city' => 'Turrubares', 'label' => 'San Pedro'],
                ['value' => 'San Juan de Mata', 'city' => 'Turrubares', 'label' => 'San Juan de Mata'],
                ['value' => 'San Luis', 'city' => 'Turrubares', 'label' => 'San Luis'],
                ['value' => 'Carara', 'city' => 'Turrubares', 'label' => 'Carara'],
                ['value' => 'Santa María', 'city' => 'Dota', 'label' => 'Santa María'],
                ['value' => 'Jardín', 'city' => 'Dota', 'label' => 'Jardín'],
                ['value' => 'Copey', 'city' => 'Dota', 'label' => 'Copey'],
                ['value' => 'Curridabat', 'city' => 'Curridabat', 'label' => 'Curridabat'],
                ['value' => 'Granadilla', 'city' => 'Curridabat', 'label' => 'Granadilla'],
                ['value' => 'Sánchez', 'city' => 'Curridabat', 'label' => 'Sánchez'],
                ['value' => 'Tirrases', 'city' => 'Curridabat', 'label' => 'Tirrases'],
                ['value' => 'San Isidro del General', 'city' => 'Pérez Zeledón', 'label' => 'San Isidro del General'],
                ['value' => 'General', 'city' => 'Pérez Zeledón', 'label' => 'General'],
                ['value' => 'Daniel Flores', 'city' => 'Pérez Zeledón', 'label' => 'Daniel Flores'],
                ['value' => 'Rivas', 'city' => 'Pérez Zeledón', 'label' => 'Rivas'],
                ['value' => 'San Pedro', 'city' => 'Pérez Zeledón', 'label' => 'San Pedro'],
                ['value' => 'Platanares', 'city' => 'Pérez Zeledón', 'label' => 'Platanares'],
                ['value' => 'Pejibaye', 'city' => 'Pérez Zeledón', 'label' => 'Pejibaye'],
                ['value' => 'Cajón', 'city' => 'Pérez Zeledón', 'label' => 'Cajón'],
                ['value' => 'Barú', 'city' => 'Pérez Zeledón', 'label' => 'Barú'],
                ['value' => 'Río Nuevo', 'city' => 'Pérez Zeledón', 'label' => 'Río Nuevo'],
                ['value' => 'Páramo', 'city' => 'Pérez Zeledón', 'label' => 'Páramo'],
                ['value' => 'San Pablo', 'city' => 'León Cortes', 'label' => 'San Pablo'],
                ['value' => 'San Andrés', 'city' => 'León Cortes', 'label' => 'San Andrés'],
                ['value' => 'Llano Bonito', 'city' => 'León Cortes', 'label' => 'Llano Bonito'],
                ['value' => 'San Isidro', 'city' => 'León Cortes', 'label' => 'San Isidro'],
                ['value' => 'Santa Cruz', 'city' => 'León Cortes', 'label' => 'Santa Cruz'],
                ['value' => 'San Antonio', 'city' => 'León Cortes', 'label' => 'San Antonio'],
                ['value' => 'Alajuela', 'city' => 'Alajuela', 'label' => 'Alajuela'],
                ['value' => 'San José', 'city' => 'Alajuela', 'label' => 'San José'],
                ['value' => 'Carrizal', 'city' => 'Alajuela', 'label' => 'Carrizal'],
                ['value' => 'San Antonio', 'city' => 'Alajuela', 'label' => 'San Antonio'],
                ['value' => 'Guácima', 'city' => 'Alajuela', 'label' => 'Guácima'],
                ['value' => 'San Isidro', 'city' => 'Alajuela', 'label' => 'San Isidro'],
                ['value' => 'Sabanilla', 'city' => 'Alajuela', 'label' => 'Sabanilla'],
                ['value' => 'San Rafael', 'city' => 'Alajuela', 'label' => 'San Rafael'],
                ['value' => 'Río Segundo', 'city' => 'Alajuela', 'label' => 'Río Segundo'],
                ['value' => 'Desamparados', 'city' => 'Alajuela', 'label' => 'Desamparados'],
                ['value' => 'Turrúcares', 'city' => 'Alajuela', 'label' => 'Turrúcares'],
                ['value' => 'Tambor', 'city' => 'Alajuela', 'label' => 'Tambor'],
                ['value' => 'Garita', 'city' => 'Alajuela', 'label' => 'Garita'],
                ['value' => 'Sarapiquí', 'city' => 'Alajuela', 'label' => 'Sarapiquí'],
                ['value' => 'San Ramón', 'city' => 'San Ramon', 'label' => 'San Ramón'],
                ['value' => 'Santiago', 'city' => 'San Ramon', 'label' => 'Santiago'],
                ['value' => 'San Juan', 'city' => 'San Ramon', 'label' => 'San Juan'],
                ['value' => 'Piedades Norte', 'city' => 'San Ramon', 'label' => 'Piedades Norte'],
                ['value' => 'Piedades Sur', 'city' => 'San Ramon', 'label' => 'Piedades Sur'],
                ['value' => 'San Rafael', 'city' => 'San Ramon', 'label' => 'San Rafael'],
                ['value' => 'San Isidro', 'city' => 'San Ramon', 'label' => 'San Isidro'],
                ['value' => 'Ángeles', 'city' => 'San Ramon', 'label' => 'Ángeles'],
                ['value' => 'Alfaro', 'city' => 'San Ramon', 'label' => 'Alfaro'],
                ['value' => 'Volio', 'city' => 'San Ramon', 'label' => 'Volio'],
                ['value' => 'Concepción', 'city' => 'San Ramon', 'label' => 'Concepción'],
                ['value' => 'Zapotal', 'city' => 'San Ramon', 'label' => 'Zapotal'],
                ['value' => 'Peñas Blancas', 'city' => 'San Ramon', 'label' => 'Peñas Blancas'],
                ['value' => 'Grecia', 'city' => 'Grecia', 'label' => 'Grecia'],
                ['value' => 'San Isidro', 'city' => 'Grecia', 'label' => 'San Isidro'],
                ['value' => 'San Jose', 'city' => 'Grecia', 'label' => 'San Jose'],
                ['value' => 'San Roque', 'city' => 'Grecia', 'label' => 'San Roque'],
                ['value' => 'Tacares', 'city' => 'Grecia', 'label' => 'Tacares'],
                ['value' => 'Río Cuarto', 'city' => 'Grecia', 'label' => 'Río Cuarto'],
                ['value' => 'Puente de Piedra', 'city' => 'Grecia', 'label' => 'Puente de Piedra'],
                ['value' => 'Bolivar', 'city' => 'Grecia', 'label' => 'Bolivar'],
                ['value' => 'San Mateo', 'city' => 'San Mateo', 'label' => 'San Mateo'],
                ['value' => 'Desmonte', 'city' => 'San Mateo', 'label' => 'Desmonte'],
                ['value' => 'Jesús María', 'city' => 'San Mateo', 'label' => 'Jesús María'],
                ['value' => 'Atenas', 'city' => 'Atenas', 'label' => 'Atenas'],
                ['value' => 'Jesús', 'city' => 'Atenas', 'label' => 'Jesús'],
                ['value' => 'Mercedes', 'city' => 'Atenas', 'label' => 'Mercedes'],
                ['value' => 'San Isidro', 'city' => 'Atenas', 'label' => 'San Isidro'],
                ['value' => 'Concepción', 'city' => 'Atenas', 'label' => 'Concepción'],
                ['value' => 'San José', 'city' => 'Atenas', 'label' => 'San José'],
                ['value' => 'Santa Eulalia', 'city' => 'Atenas', 'label' => 'Santa Eulalia'],
                ['value' => 'Escobal', 'city' => 'Atenas', 'label' => 'Escobal'],
                ['value' => 'Naranjo', 'city' => 'Naranjo', 'label' => 'Naranjo'],
                ['value' => 'San Miguel', 'city' => 'Naranjo', 'label' => 'San Miguel'],
                ['value' => 'San José', 'city' => 'Naranjo', 'label' => 'San José'],
                ['value' => 'Cirrí Sur', 'city' => 'Naranjo', 'label' => 'Cirrí Sur'],
                ['value' => 'San Jerónimo', 'city' => 'Naranjo', 'label' => 'San Jerónimo'],
                ['value' => 'San Juan', 'city' => 'Naranjo', 'label' => 'San Juan'],
                ['value' => 'Rosario', 'city' => 'Naranjo', 'label' => 'Rosario'],
                ['value' => 'Palmares', 'city' => 'Palmares', 'label' => 'Palmares'],
                ['value' => 'Zaragoza', 'city' => 'Palmares', 'label' => 'Zaragoza'],
                ['value' => 'Buenos Aires', 'city' => 'Palmares', 'label' => 'Buenos Aires'],
                ['value' => 'Santiago', 'city' => 'Palmares', 'label' => 'Santiago'],
                ['value' => 'Candelaria', 'city' => 'Palmares', 'label' => 'Candelaria'],
                ['value' => 'Esquipulas', 'city' => 'Palmares', 'label' => 'Esquipulas'],
                ['value' => 'Granja', 'city' => 'Palmares', 'label' => 'Granja'],
                ['value' => 'San Pedro', 'city' => 'Poás', 'label' => 'San Pedro'],
                ['value' => 'San Juan', 'city' => 'Poás', 'label' => 'San Juan'],
                ['value' => 'San Rafael', 'city' => 'Poás', 'label' => 'San Rafael'],
                ['value' => 'Carrillos', 'city' => 'Poás', 'label' => 'Carrillos'],
                ['value' => 'Sabana Redonda', 'city' => 'Poás', 'label' => 'Sabana Redonda'],
                ['value' => 'Orotina', 'city' => 'Orotina', 'label' => 'Orotina'],
                ['value' => 'Mastate', 'city' => 'Orotina', 'label' => 'Mastate'],
                ['value' => 'Hacienda Vieja', 'city' => 'Orotina', 'label' => 'Hacienda Vieja'],
                ['value' => 'Coyolar', 'city' => 'Orotina', 'label' => 'Coyolar'],
                ['value' => 'Ceiba', 'city' => 'Orotina', 'label' => 'Ceiba'],
                ['value' => 'Quesada', 'city' => 'San Carlos', 'label' => 'Quesada'],
                ['value' => 'Florencia', 'city' => 'San Carlos', 'label' => 'Florencia'],
                ['value' => 'Buenavista', 'city' => 'San Carlos', 'label' => 'Buenavista'],
                ['value' => 'Aguas Zarcas', 'city' => 'San Carlos', 'label' => 'Aguas Zarcas'],
                ['value' => 'Venecia', 'city' => 'San Carlos', 'label' => 'Venecia'],
                ['value' => 'Pital', 'city' => 'San Carlos', 'label' => 'Pital'],
                ['value' => 'Fortuna', 'city' => 'San Carlos', 'label' => 'Fortuna'],
                ['value' => 'Tigra', 'city' => 'San Carlos', 'label' => 'Tigra'],
                ['value' => 'Palmera', 'city' => 'San Carlos', 'label' => 'Palmera'],
                ['value' => 'Venado', 'city' => 'San Carlos', 'label' => 'Venado'],
                ['value' => 'Cutris', 'city' => 'San Carlos', 'label' => 'Cutris'],
                ['value' => 'Monterrey', 'city' => 'San Carlos', 'label' => 'Monterrey'],
                ['value' => 'Pocosol', 'city' => 'San Carlos', 'label' => 'Pocosol'],
                ['value' => 'Zarcero', 'city' => 'Alfaro Ruiz', 'label' => 'Zarcero'],
                ['value' => 'Laguna', 'city' => 'Alfaro Ruiz', 'label' => 'Laguna'],
                ['value' => 'Tapezco', 'city' => 'Alfaro Ruiz', 'label' => 'Tapezco'],
                ['value' => 'Guadalupe', 'city' => 'Alfaro Ruiz', 'label' => 'Guadalupe'],
                ['value' => 'Palmira', 'city' => 'Alfaro Ruiz', 'label' => 'Palmira'],
                ['value' => 'Zapote', 'city' => 'Alfaro Ruiz', 'label' => 'Zapote'],
                ['value' => 'Brisas', 'city' => 'Alfaro Ruiz', 'label' => 'Brisas'],
                ['value' => 'Sarchi Norte', 'city' => 'Valverde Vega', 'label' => 'Sarchi Norte'],
                ['value' => 'Sarchi Sur', 'city' => 'Valverde Vega', 'label' => 'Sarchi Sur'],
                ['value' => 'Toro Amarillo', 'city' => 'Valverde Vega', 'label' => 'Toro Amarillo'],
                ['value' => 'San Pedro', 'city' => 'Valverde Vega', 'label' => 'San Pedro'],
                ['value' => 'Rodriguez', 'city' => 'Valverde Vega', 'label' => 'Rodriguez'],
                ['value' => 'Upala', 'city' => 'Upala', 'label' => 'Upala'],
                ['value' => 'Aguas Claras', 'city' => 'Upala', 'label' => 'Aguas Claras'],
                ['value' => 'San Jose (Pizote)', 'city' => 'Upala', 'label' => 'San Jose (Pizote)'],
                ['value' => 'Bijagua', 'city' => 'Upala', 'label' => 'Bijagua'],
                ['value' => 'Delicias', 'city' => 'Upala', 'label' => 'Delicias'],
                ['value' => 'Dos Rios', 'city' => 'Upala', 'label' => 'Dos Rios'],
                ['value' => 'Yoliyllal', 'city' => 'Upala', 'label' => 'Yoliyllal'],
                ['value' => 'Los Chiles', 'city' => 'Los Chiles', 'label' => 'Los Chiles'],
                ['value' => 'Caño Negro', 'city' => 'Los Chiles', 'label' => 'Caño Negro'],
                ['value' => 'El Amparo', 'city' => 'Los Chiles', 'label' => 'El Amparo'],
                ['value' => 'San Jorge', 'city' => 'Los Chiles', 'label' => 'San Jorge'],
                ['value' => 'San Rafael', 'city' => 'Guatuso', 'label' => 'San Rafael'],
                ['value' => 'Buenavista', 'city' => 'Guatuso', 'label' => 'Buenavista'],
                ['value' => 'Cote', 'city' => 'Guatuso', 'label' => 'Cote'],
                ['value' => 'Oriental', 'city' => 'Cartago', 'label' => 'Oriental'],
                ['value' => 'Occidental', 'city' => 'Cartago', 'label' => 'Occidental'],
                ['value' => 'Carmen', 'city' => 'Cartago', 'label' => 'Carmen'],
                ['value' => 'San Nicolas', 'city' => 'Cartago', 'label' => 'San Nicolas'],
                ['value' => 'Aguacaliente (San Francisco)', 'city' => 'Cartago', 'label' => 'Aguacaliente (San Francisco)'],
                ['value' => 'Guadalupe (Arenilla)', 'city' => 'Cartago', 'label' => 'Guadalupe (Arenilla)'],
                ['value' => 'Corralillo', 'city' => 'Cartago', 'label' => 'Corralillo'],
                ['value' => 'Tierra Blanca', 'city' => 'Cartago', 'label' => 'Tierra Blanca'],
                ['value' => 'Dulce Nombre', 'city' => 'Cartago', 'label' => 'Dulce Nombre'],
                ['value' => 'Llano Grande', 'city' => 'Cartago', 'label' => 'Llano Grande'],
                ['value' => 'Quebradilla', 'city' => 'Cartago', 'label' => 'Quebradilla'],
                ['value' => 'Paraiso', 'city' => 'Paraíso', 'label' => 'Paraiso'],
                ['value' => 'Santiago', 'city' => 'Paraíso', 'label' => 'Santiago'],
                ['value' => 'Orosi', 'city' => 'Paraíso', 'label' => 'Orosi'],
                ['value' => 'Cachi', 'city' => 'Paraíso', 'label' => 'Cachi'],
                ['value' => 'Llanos de Santa Lucia', 'city' => 'Paraíso', 'label' => 'Llanos de Santa Lucia'],
                ['value' => 'Tres Rios', 'city' => 'La Unión', 'label' => 'Tres Rios'],
                ['value' => 'San Diego', 'city' => 'La Unión', 'label' => 'San Diego'],
                ['value' => 'San Juan', 'city' => 'La Unión', 'label' => 'San Juan'],
                ['value' => 'San Rafael', 'city' => 'La Unión', 'label' => 'San Rafael'],
                ['value' => 'Concepcion', 'city' => 'La Unión', 'label' => 'Concepcion'],
                ['value' => 'Dulce Nombre', 'city' => 'La Unión', 'label' => 'Dulce Nombre'],
                ['value' => 'San Ramon', 'city' => 'La Unión', 'label' => 'San Ramon'],
                ['value' => 'Rio Azul', 'city' => 'La Unión', 'label' => 'Rio Azul'],
                ['value' => 'Juan Viñas', 'city' => 'Jiménez', 'label' => 'Juan Viñas'],
                ['value' => 'Tucurrique', 'city' => 'Jiménez', 'label' => 'Tucurrique'],
                ['value' => 'Pejibaye', 'city' => 'Jiménez', 'label' => 'Pejibaye'],
                ['value' => 'Turrialba', 'city' => 'Turrialba', 'label' => 'Turrialba'],
                ['value' => 'La Suiza', 'city' => 'Turrialba', 'label' => 'La Suiza'],
                ['value' => 'Peralta', 'city' => 'Turrialba', 'label' => 'Peralta'],
                ['value' => 'Santa Cruz', 'city' => 'Turrialba', 'label' => 'Santa Cruz'],
                ['value' => 'Santa Teresita', 'city' => 'Turrialba', 'label' => 'Santa Teresita'],
                ['value' => 'Pavones', 'city' => 'Turrialba', 'label' => 'Pavones'],
                ['value' => 'Tuis', 'city' => 'Turrialba', 'label' => 'Tuis'],
                ['value' => 'Tayutic', 'city' => 'Turrialba', 'label' => 'Tayutic'],
                ['value' => 'Santa Rosa', 'city' => 'Turrialba', 'label' => 'Santa Rosa'],
                ['value' => 'Tres Equis', 'city' => 'Turrialba', 'label' => 'Tres Equis'],
                ['value' => 'La Isabel', 'city' => 'Turrialba', 'label' => 'La Isabel'],
                ['value' => 'Chirripo', 'city' => 'Turrialba', 'label' => 'Chirripo'],
                ['value' => 'Pacayas', 'city' => 'Alvarado', 'label' => 'Pacayas'],
                ['value' => 'Cervantes', 'city' => 'Alvarado', 'label' => 'Cervantes'],
                ['value' => 'Capellades', 'city' => 'Alvarado', 'label' => 'Capellades'],
                ['value' => 'San Rafael', 'city' => 'Oreamuno', 'label' => 'San Rafael'],
                ['value' => 'Cote', 'city' => 'Oreamuno', 'label' => 'Cote'],
                ['value' => 'Potrero Cerrado', 'city' => 'Oreamuno', 'label' => 'Potrero Cerrado'],
                ['value' => 'Cipreses', 'city' => 'Oreamuno', 'label' => 'Cipreses'],
                ['value' => 'Santa Rosa', 'city' => 'Oreamuno', 'label' => 'Santa Rosa'],
                ['value' => 'Tejar', 'city' => 'El Guarco', 'label' => 'Tejar'],
                ['value' => 'San Isidro', 'city' => 'El Guarco', 'label' => 'San Isidro'],
                ['value' => 'Tobosi', 'city' => 'El Guarco', 'label' => 'Tobosi'],
                ['value' => 'Patio de Agua', 'city' => 'El Guarco', 'label' => 'Patio de Agua'],
                ['value' => 'Heredia', 'city' => 'Heredia', 'label' => 'Heredia'],
                ['value' => 'Mercedes', 'city' => 'Heredia', 'label' => 'Mercedes'],
                ['value' => 'San Francisco', 'city' => 'Heredia', 'label' => 'San Francisco'],
                ['value' => 'Ulloa', 'city' => 'Heredia', 'label' => 'Ulloa'],
                ['value' => 'Varablanca', 'city' => 'Heredia', 'label' => 'Varablanca'],
                ['value' => 'Barva', 'city' => 'Barva', 'label' => 'Barva'],
                ['value' => 'San Pedro', 'city' => 'Barva', 'label' => 'San Pedro'],
                ['value' => 'San Pablo', 'city' => 'Barva', 'label' => 'San Pablo'],
                ['value' => 'San Roque', 'city' => 'Barva', 'label' => 'San Roque'],
                ['value' => 'Santa Lucia', 'city' => 'Barva', 'label' => 'Santa Lucia'],
                ['value' => 'San Jose de la Montaña', 'city' => 'Barva', 'label' => 'San Jose de la Montaña'],
                ['value' => 'Santo Domingo', 'city' => 'Santo Domingo', 'label' => 'Santo Domingo'],
                ['value' => 'San Vicente', 'city' => 'Santo Domingo', 'label' => 'San Vicente'],
                ['value' => 'San Miguel', 'city' => 'Santo Domingo', 'label' => 'San Miguel'],
                ['value' => 'Paracito', 'city' => 'Santo Domingo', 'label' => 'Paracito'],
                ['value' => 'Santo Tomas', 'city' => 'Santo Domingo', 'label' => 'Santo Tomas'],
                ['value' => 'Santa Rosa', 'city' => 'Santo Domingo', 'label' => 'Santa Rosa'],
                ['value' => 'Tures', 'city' => 'Santo Domingo', 'label' => 'Tures'],
                ['value' => 'Para', 'city' => 'Santo Domingo', 'label' => 'Para'],
                ['value' => 'Santa Barbara', 'city' => 'Santa Bárbara', 'label' => 'Santa Barbara'],
                ['value' => 'San Pedro', 'city' => 'Santa Bárbara', 'label' => 'San Pedro'],
                ['value' => 'San Juan', 'city' => 'Santa Bárbara', 'label' => 'San Juan'],
                ['value' => 'Jesus', 'city' => 'Santa Bárbara', 'label' => 'Jesus'],
                ['value' => 'Santo Domingo', 'city' => 'Santa Bárbara', 'label' => 'Santo Domingo'],
                ['value' => 'Puraba', 'city' => 'Santa Bárbara', 'label' => 'Puraba'],
                ['value' => 'San Rafael', 'city' => 'San Rafael', 'label' => 'San Rafael'],
                ['value' => 'San Josecito', 'city' => 'San Rafael', 'label' => 'San Josecito'],
                ['value' => 'Santiago', 'city' => 'San Rafael', 'label' => 'Santiago'],
                ['value' => 'angeles', 'city' => 'San Rafael', 'label' => 'angeles'],
                ['value' => 'Concepcion', 'city' => 'San Rafael', 'label' => 'Concepcion'],
                ['value' => 'San Isidro', 'city' => 'San Isidro', 'label' => 'San Isidro'],
                ['value' => 'San Jose', 'city' => 'San Isidro', 'label' => 'San Jose'],
                ['value' => 'Concepcion', 'city' => 'San Isidro', 'label' => 'Concepcion'],
                ['value' => 'San Francisco', 'city' => 'San Isidro', 'label' => 'San Francisco'],
                ['value' => 'San Antonio', 'city' => 'Belén', 'label' => 'San Antonio'],
                ['value' => 'Ribera', 'city' => 'Belén', 'label' => 'Ribera'],
                ['value' => 'Asuncion', 'city' => 'Belén', 'label' => 'Asuncion'],
                ['value' => 'San Joaquin de Flores', 'city' => 'San Joaquín de Flores', 'label' => 'San Joaquin de Flores'],
                ['value' => 'Barrantes', 'city' => 'San Joaquín de Flores', 'label' => 'Barrantes'],
                ['value' => 'Llorente', 'city' => 'San Joaquín de Flores', 'label' => 'Llorente'],
                ['value' => 'San Pablo', 'city' => 'San Pablo', 'label' => 'San Pablo'],
                ['value' => 'Puerto Viejo', 'city' => 'Sarapiquí', 'label' => 'Puerto Viejo'],
                ['value' => 'La Virgen', 'city' => 'Sarapiquí', 'label' => 'La Virgen'],
                ['value' => 'Horquetas', 'city' => 'Sarapiquí', 'label' => 'Horquetas'],
                ['value' => 'Llanuras del Gaspar', 'city' => 'Sarapiquí', 'label' => 'Llanuras del Gaspar'],
                ['value' => 'Cureña', 'city' => 'Sarapiquí', 'label' => 'Cureña'],
                ['value' => 'Liberia', 'city' => 'Liberia', 'label' => 'Liberia'],
                ['value' => 'Cañas Dulces', 'city' => 'Liberia', 'label' => 'Cañas Dulces'],
                ['value' => 'Mayorga', 'city' => 'Liberia', 'label' => 'Mayorga'],
                ['value' => 'Nacascolo', 'city' => 'Liberia', 'label' => 'Nacascolo'],
                ['value' => 'Curubande', 'city' => 'Liberia', 'label' => 'Curubande'],
                ['value' => 'Nicoya', 'city' => 'Nicoya', 'label' => 'Nicoya'],
                ['value' => 'Mansion', 'city' => 'Nicoya', 'label' => 'Mansion'],
                ['value' => 'San Antonio', 'city' => 'Nicoya', 'label' => 'San Antonio'],
                ['value' => 'Quebrada Honda', 'city' => 'Nicoya', 'label' => 'Quebrada Honda'],
                ['value' => 'Samara', 'city' => 'Nicoya', 'label' => 'Samara'],
                ['value' => 'Nosara', 'city' => 'Nicoya', 'label' => 'Nosara'],
                ['value' => 'Belen de Nosarita', 'city' => 'Nicoya', 'label' => 'Belen de Nosarita'],
                ['value' => 'Santa Cruz', 'city' => 'Santa Cruz', 'label' => 'Santa Cruz'],
                ['value' => 'Bolson', 'city' => 'Santa Cruz', 'label' => 'Bolson'],
                ['value' => 'Veintisiete de Abril', 'city' => 'Santa Cruz', 'label' => 'Veintisiete de Abril'],
                ['value' => 'Tempate', 'city' => 'Santa Cruz', 'label' => 'Tempate'],
                ['value' => 'Cartagena', 'city' => 'Santa Cruz', 'label' => 'Cartagena'],
                ['value' => 'Cuajiniquil', 'city' => 'Santa Cruz', 'label' => 'Cuajiniquil'],
                ['value' => 'Diria', 'city' => 'Santa Cruz', 'label' => 'Diria'],
                ['value' => 'Cabo Velas', 'city' => 'Santa Cruz', 'label' => 'Cabo Velas'],
                ['value' => 'Tamarindo', 'city' => 'Santa Cruz', 'label' => 'Tamarindo'],
                ['value' => 'Bagaces', 'city' => 'Bagaces', 'label' => 'Bagaces'],
                ['value' => 'Fortuna', 'city' => 'Bagaces', 'label' => 'Fortuna'],
                ['value' => 'Mogote', 'city' => 'Bagaces', 'label' => 'Mogote'],
                ['value' => 'Rio Naranjo', 'city' => 'Bagaces', 'label' => 'Rio Naranjo'],
                ['value' => 'Filadelfia', 'city' => 'Carrillo', 'label' => 'Filadelfia'],
                ['value' => 'Palmira', 'city' => 'Carrillo', 'label' => 'Palmira'],
                ['value' => 'Sardinal', 'city' => 'Carrillo', 'label' => 'Sardinal'],
                ['value' => 'Belen', 'city' => 'Carrillo', 'label' => 'Belen'],
                ['value' => 'Cañas', 'city' => 'Cañas', 'label' => 'Cañas'],
                ['value' => 'Palmira', 'city' => 'Cañas', 'label' => 'Palmira'],
                ['value' => 'San Miguel', 'city' => 'Cañas', 'label' => 'San Miguel'],
                ['value' => 'Bebedero', 'city' => 'Cañas', 'label' => 'Bebedero'],
                ['value' => 'Porozal', 'city' => 'Cañas', 'label' => 'Porozal'],
                ['value' => 'Juntas', 'city' => 'Abangares', 'label' => 'Juntas'],
                ['value' => 'Sierra', 'city' => 'Abangares', 'label' => 'Sierra'],
                ['value' => 'San Juan', 'city' => 'Abangares', 'label' => 'San Juan'],
                ['value' => 'Colorado', 'city' => 'Abangares', 'label' => 'Colorado'],
                ['value' => 'Tilaran', 'city' => 'Tilarán', 'label' => 'Tilaran'],
                ['value' => 'Quebrada Grande', 'city' => 'Tilarán', 'label' => 'Quebrada Grande'],
                ['value' => 'Tronadora', 'city' => 'Tilarán', 'label' => 'Tronadora'],
                ['value' => 'Santa Rosa', 'city' => 'Tilarán', 'label' => 'Santa Rosa'],
                ['value' => 'Libano', 'city' => 'Tilarán', 'label' => 'Libano'],
                ['value' => 'Tierras Morenas', 'city' => 'Tilarán', 'label' => 'Tierras Morenas'],
                ['value' => 'Arenal', 'city' => 'Tilarán', 'label' => 'Arenal'],
                ['value' => 'Carmona', 'city' => 'Nandayure', 'label' => 'Carmona'],
                ['value' => 'Santa Rita', 'city' => 'Nandayure', 'label' => 'Santa Rita'],
                ['value' => 'Zapotal', 'city' => 'Nandayure', 'label' => 'Zapotal'],
                ['value' => 'San Pablo', 'city' => 'Nandayure', 'label' => 'San Pablo'],
                ['value' => 'Porvenir', 'city' => 'Nandayure', 'label' => 'Porvenir'],
                ['value' => 'Bejuco', 'city' => 'Nandayure', 'label' => 'Bejuco'],
                ['value' => 'La Cruz', 'city' => 'La Cruz', 'label' => 'La Cruz'],
                ['value' => 'Santa Cecilia', 'city' => 'La Cruz', 'label' => 'Santa Cecilia'],
                ['value' => 'Garita', 'city' => 'La Cruz', 'label' => 'Garita'],
                ['value' => 'Santa Elena', 'city' => 'La Cruz', 'label' => 'Santa Elena'],
                ['value' => 'Hojancha', 'city' => 'Hojancha', 'label' => 'Hojancha'],
                ['value' => 'Monte Romo', 'city' => 'Hojancha', 'label' => 'Monte Romo'],
                ['value' => 'Puerto Carrillo', 'city' => 'Hojancha', 'label' => 'Puerto Carrillo'],
                ['value' => 'Huacas', 'city' => 'Hojancha', 'label' => 'Huacas'],
                ['value' => 'Puntarenas', 'city' => 'Puntarenas', 'label' => 'Puntarenas'],
                ['value' => 'Pitahaya', 'city' => 'Puntarenas', 'label' => 'Pitahaya'],
                ['value' => 'Chomes', 'city' => 'Puntarenas', 'label' => 'Chomes'],
                ['value' => 'Lepanto', 'city' => 'Puntarenas', 'label' => 'Lepanto'],
                ['value' => 'Paquera', 'city' => 'Puntarenas', 'label' => 'Paquera'],
                ['value' => 'Manzanillo', 'city' => 'Puntarenas', 'label' => 'Manzanillo'],
                ['value' => 'Guacimal', 'city' => 'Puntarenas', 'label' => 'Guacimal'],
                ['value' => 'Barranca', 'city' => 'Puntarenas', 'label' => 'Barranca'],
                ['value' => 'Monte Verde', 'city' => 'Puntarenas', 'label' => 'Monte Verde'],
                ['value' => 'Isla del Coco', 'city' => 'Puntarenas', 'label' => 'Isla del Coco'],
                ['value' => 'Cobano', 'city' => 'Puntarenas', 'label' => 'Cobano'],
                ['value' => 'Chacarita', 'city' => 'Puntarenas', 'label' => 'Chacarita'],
                ['value' => 'Chira', 'city' => 'Puntarenas', 'label' => 'Chira'],
                ['value' => 'Acapulco', 'city' => 'Puntarenas', 'label' => 'Acapulco'],
                ['value' => 'El Roble', 'city' => 'Puntarenas', 'label' => 'El Roble'],
                ['value' => 'Arancibia', 'city' => 'Puntarenas', 'label' => 'Arancibia'],
                ['value' => 'Espiritu Santo', 'city' => 'Esparza', 'label' => 'Espiritu Santo'],
                ['value' => 'San Juan Grande', 'city' => 'Esparza', 'label' => 'San Juan Grande'],
                ['value' => 'Macacona', 'city' => 'Esparza', 'label' => 'Macacona'],
                ['value' => 'San Rafael', 'city' => 'Esparza', 'label' => 'San Rafael'],
                ['value' => 'San Jeronimo', 'city' => 'Esparza', 'label' => 'San Jeronimo'],
                ['value' => 'Buenos Aires', 'city' => 'Buenos Aires', 'label' => 'Buenos Aires'],
                ['value' => 'Volcan', 'city' => 'Buenos Aires', 'label' => 'Volcan'],
                ['value' => 'Potrero Grande', 'city' => 'Buenos Aires', 'label' => 'Potrero Grande'],
                ['value' => 'Boruca', 'city' => 'Buenos Aires', 'label' => 'Boruca'],
                ['value' => 'Pilas', 'city' => 'Buenos Aires', 'label' => 'Pilas'],
                ['value' => 'Colinas', 'city' => 'Buenos Aires', 'label' => 'Colinas'],
                ['value' => 'Changena', 'city' => 'Buenos Aires', 'label' => 'Changena'],
                ['value' => 'Briolley', 'city' => 'Buenos Aires', 'label' => 'Briolley'],
                ['value' => 'Brunka', 'city' => 'Buenos Aires', 'label' => 'Brunka'],
                ['value' => 'Miramar', 'city' => 'Montes de Oro', 'label' => 'Miramar'],
                ['value' => 'Union', 'city' => 'Montes de Oro', 'label' => 'Union'],
                ['value' => 'San Isidro', 'city' => 'Montes de Oro', 'label' => 'San Isidro'],
                ['value' => 'Puerto Cortes', 'city' => 'Osa', 'label' => 'Puerto Cortes'],
                ['value' => 'Palmar', 'city' => 'Osa', 'label' => 'Palmar'],
                ['value' => 'Sierpe', 'city' => 'Osa', 'label' => 'Sierpe'],
                ['value' => 'Bahia Ballena', 'city' => 'Osa', 'label' => 'Bahia Ballena'],
                ['value' => 'Piedras Blancas', 'city' => 'Osa', 'label' => 'Piedras Blancas'],
                ['value' => 'Quepos', 'city' => 'Aguirre', 'label' => 'Quepos'],
                ['value' => 'Savegre', 'city' => 'Aguirre', 'label' => 'Savegre'],
                ['value' => 'Naranjito', 'city' => 'Aguirre', 'label' => 'Naranjito'],
                ['value' => 'Golfito', 'city' => 'Golfito', 'label' => 'Golfito'],
                ['value' => 'Puerto Jimenez', 'city' => 'Golfito', 'label' => 'Puerto Jimenez'],
                ['value' => 'Guaycara', 'city' => 'Golfito', 'label' => 'Guaycara'],
                ['value' => 'Pavon', 'city' => 'Golfito', 'label' => 'Pavon'],
                ['value' => 'San Vito', 'city' => 'Coto Brus', 'label' => 'San Vito'],
                ['value' => 'Sabalito', 'city' => 'Coto Brus', 'label' => 'Sabalito'],
                ['value' => 'Aguabuena', 'city' => 'Coto Brus', 'label' => 'Aguabuena'],
                ['value' => 'Limoncito', 'city' => 'Coto Brus', 'label' => 'Limoncito'],
                ['value' => 'Pittier', 'city' => 'Coto Brus', 'label' => 'Pittier'],
                ['value' => 'Parrita', 'city' => 'Parrita', 'label' => 'Parrita'],
                ['value' => 'Corredor', 'city' => 'Corredores', 'label' => 'Corredor'],
                ['value' => 'La Cuesta', 'city' => 'Corredores', 'label' => 'La Cuesta'],
                ['value' => 'Canoas', 'city' => 'Corredores', 'label' => 'Canoas'],
                ['value' => 'Laurel', 'city' => 'Corredores', 'label' => 'Laurel'],
                ['value' => 'Jaco', 'city' => 'Garabito', 'label' => 'Jaco'],
                ['value' => 'Tarcoles', 'city' => 'Garabito', 'label' => 'Tarcoles'],
                ['value' => 'Limon', 'city' => 'Limón', 'label' => 'Limon'],
                ['value' => 'Valle La Estrella', 'city' => 'Limón', 'label' => 'Valle La Estrella'],
                ['value' => 'Rio Blanco', 'city' => 'Limón', 'label' => 'Rio Blanco'],
                ['value' => 'Matama', 'city' => 'Limón', 'label' => 'Matama'],
                ['value' => 'Guapiles', 'city' => 'Pococí', 'label' => 'Guapiles'],
                ['value' => 'Jimenez', 'city' => 'Pococí', 'label' => 'Jimenez'],
                ['value' => 'Rita', 'city' => 'Pococí', 'label' => 'Rita'],
                ['value' => 'Roxana', 'city' => 'Pococí', 'label' => 'Roxana'],
                ['value' => 'Cariari', 'city' => 'Pococí', 'label' => 'Cariari'],
                ['value' => 'Colorado', 'city' => 'Pococí', 'label' => 'Colorado'],
                ['value' => 'Siquirres', 'city' => 'Siquirres', 'label' => 'Siquirres'],
                ['value' => 'Pacuarito', 'city' => 'Siquirres', 'label' => 'Pacuarito'],
                ['value' => 'Florida', 'city' => 'Siquirres', 'label' => 'Florida'],
                ['value' => 'Germania', 'city' => 'Siquirres', 'label' => 'Germania'],
                ['value' => 'Cairo', 'city' => 'Siquirres', 'label' => 'Cairo'],
                ['value' => 'Alegria', 'city' => 'Siquirres', 'label' => 'Alegria'],
                ['value' => 'Bratsi', 'city' => 'Talamanca', 'label' => 'Bratsi'],
                ['value' => 'Sixaola', 'city' => 'Talamanca', 'label' => 'Sixaola'],
                ['value' => 'Cahuita', 'city' => 'Talamanca', 'label' => 'Cahuita'],
                ['value' => 'Telire', 'city' => 'Talamanca', 'label' => 'Telire'],
                ['value' => 'Matina', 'city' => 'Matina', 'label' => 'Matina'],
                ['value' => 'Battan', 'city' => 'Matina', 'label' => 'Battan'],
                ['value' => 'Carrandi', 'city' => 'Matina', 'label' => 'Carrandi'],
                ['value' => 'Guacimo', 'city' => 'Guácimo', 'label' => 'Guacimo'],
                ['value' => 'Mercedes', 'city' => 'Guácimo', 'label' => 'Mercedes'],
                ['value' => 'Pocora', 'city' => 'Guácimo', 'label' => 'Pocora'],
                ['value' => 'Rio Jimenez', 'city' => 'Guácimo', 'label' => 'Rio Jimenez'],
                ['value' => 'Duacari', 'city' => 'Guácimo', 'label' => 'Duacari']
			];
			
			echo json_encode($options, JSON_PRETTY_PRINT);